### ISSUE TITLE
Error in network training

### ISSUE THREAD

**Issue by caisy417** [thangvubk/video-super-resolution#7]
When I try to execute train.py, I met this error.

-------YOUR SETTINGS_________
        verbose: True
          model: VRES
      train_set: train
      fine_tune: False
     num_epochs: 50
     batch_size: 100
  learning_rate: 0.001
          scale: 3

Contructing dataset...
Training...
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    main()
  File "train.py", line 74, in main
    solver.train(train_dataset)
  File "C:\Users\csy\Documents\video-super-resolution-master\solver.py", line 233, in train
    self._epoch_step(train_dataset, epoch)
  File "C:\Users\csy\Documents\video-super-resolution-master\solver.py", line 101, in _epoch_step
    running_loss += loss.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by thangvubk** [comment]
I guess you are using new PyTorch version. As the error says, you may change ``loss.data[0]`` to ``loss.item()`` to fix the problem.

**Comment by caisy417** [comment]
Yes, the problem is solved! Thank you!
But other errors appeared...

-------YOUR SETTINGS_________
          model: VRES
  learning_rate: 0.001
        verbose: True
      train_set: train
     batch_size: 100
     num_epochs: 50
      fine_tune: False
          scale: 3

Contructing dataset...
Training...
C:\Users\csy\Documents\video-super-resolution-master\solver.py:105: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(self.model.parameters(), 0.4)
100% (622 of 622) |###############################################################| Elapsed Time: 0:12:48 ETA:  0:00:00Epoch      0, loss 0.01080
Computing PSNR...
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    main()
  File "train.py", line 74, in main
    solver.train(train_dataset)
  File "C:\Users\csy\Documents\video-super-resolution-master\solver.py", line 240, in train
    train_psnr, train_ssim, _, _ = self._check_PSNR(train_dataset)
  File "C:\Users\csy\Documents\video-super-resolution-master\solver.py", line 163, in _check_PSNR
    for batch, (input_batch, label_batch) in enumerate(dataloader):
  File "C:\Users\csy\Anaconda3\envs\video\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\csy\Anaconda3\envs\video\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument

(video) C:\Users\csy\Documents\video-super-resolution-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Comment by thangvubk** [comment]
I will check it again and let u know

**Comment by LINSEVENQI** [comment]
I meet the problem also.Have you solved this problem? Can you tell me?

**Comment by LINSEVENQI** [comment]
Traceback (most recent call last):
  File "D:/LQwork/video-super-resolution-master-oral/video-super-resolution-master/train.py", line 78, in <module>
    main()
  File "D:/LQwork/video-super-resolution-master-oral/video-super-resolution-master/train.py", line 76, in main
    solver.train(train_dataset)
  File "D:\LQwork\video-super-resolution-master-oral\video-super-resolution-master\solver.py", line 242, in train
    self._epoch_step(train_dataset, epoch)
  File "D:\LQwork\video-super-resolution-master-oral\video-super-resolution-master\solver.py", line 89, in _epoch_step
    for i, (input_batch, label_batch) in enumerate(dataloader):
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "D:\Anaconda\envs\pytorch\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\envs\pytorch\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

Process finished with exit code 1

**Comment by thangvubk** [comment]
I have run the code sucessfully. Are you using window?

**Comment by caisy417** [comment]
> I have run the code sucessfully. Are you using window?

yes

**Comment by thangvubk** [comment]
I dont have window server to test the code. You may try to tun the code on Linux or figure out to handle the problem based on error mesage.

**Comment by caisy417** [comment]
> I dont have window server to test the code. You may try to tun the code on Linux or figure out to handle the problem based on error mesage.

Thank you. I will try it out.

**Comment by LINSEVENQI** [comment]
> Yes, the problem is solved! Thank you!
> But other errors appeared...
> 
> -------YOUR SETTINGS_________
> model: VRES
> learning_rate: 0.001
> verbose: True
> train_set: train
> batch_size: 100
> num_epochs: 50
> fine_tune: False
> scale: 3
> 
> Contructing dataset...
> Training...
> C:\Users\csy\Documents\video-super-resolution-master\solver.py:105: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
> nn.utils.clip_grad_norm(self.model.parameters(), 0.4)
> 100% (622 of 622) |###############################################################| Elapsed Time: 0:12:48 ETA: 0:00:00Epoch 0, loss 0.01080
> Computing PSNR...
> Traceback (most recent call last):
> File "train.py", line 76, in 
> main()
> File "train.py", line 74, in main
> solver.train(train_dataset)
> File "C:\Users\csy\Documents\video-super-resolution-master\solver.py", line 240, in train
> train_psnr, train_ssim, _, _ = self._check_PSNR(train_dataset)
> File "C:\Users\csy\Documents\video-super-resolution-master\solver.py", line 163, in _check_PSNR
> for batch, (input_batch, label_batch) in enumerate(dataloader):
> File "C:\Users\csy\Anaconda3\envs\video\lib\site-packages\torch\utils\data\dataloader.py", line 193, in **iter**
> return _DataLoaderIter(self)
> File "C:\Users\csy\Anaconda3\envs\video\lib\site-packages\torch\utils\data\dataloader.py", line 469, in **init**
> w.start()
> File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\context.py", line 212, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\context.py", line 313, in _Popen
> return Popen(process_obj)
> File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\popen_spawn_win32.py", line 66, in **init**
> reduction.dump(process_obj, to_child)
> File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\reduction.py", line 59, in dump
> ForkingPickler(file, protocol).dump(obj)
> OSError: [Errno 22] Invalid argument
> 
> (video) C:\Users\csy\Documents\video-super-resolution-master>Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\spawn.py", line 106, in spawn_main
> exitcode = _main(fd)
> File "C:\Users\csy\Anaconda3\envs\video\lib\multiprocessing\spawn.py", line 116, in _main
> self = pickle.load(from_parent)
> EOFError: Ran out of input
Can you tell me if you solve this problem? I have not found a solution.Thanks!

**Comment by LINSEVENQI** [comment]
> I dont have window server to test the code. You may try to tun the code on Linux or figure out to handle the problem based on error mesage.

when I set the num_workers=0,this problem is salved ! However, I still have a question, how to use your code to save the best training model, because I see the prompt "best_model_state" is not used, and how to set "fine_tune" and "verbose" to True,I tried a few times but still showing False, Thank you very much!

**Comment by thangvubk** [comment]
I wll revise it soon.

**Comment by LINSEVENQI** [comment]
> I wll revise it soon.

 # capture best model
        best_val_psnr = -1
        best_model_state = self.model.state_dict()
 # capture running PSNR on train and val dataset
        train_psnr, train_ssim, _, _ = self._check_PSNR(train_dataset)
        self.hist_train_psnr.append(train_psnr)
When I read these code I have some questions,I don't understand how to capture best model and I don't know where use the val dataset.I am very embarrassed to bother you many times, but I really want to know the answers to these questions.Thank you very much!!!!!!!!!!!!!!!!!

**Comment by thangvubk** [comment]
Saving model with best val PSNR is supported from [16dfac2](https://github.com/thangvubk/video-super-resolution/commit/16dfac27fc52ac14f6b38bce71378c9bd1288261)

**Comment by thangvubk** [comment]
> when I set the num_workers=0,this problem is salved ! However, I still have a question, how to use your code to save the best training model, because I see the prompt "best_model_state" is not used, and how to set "fine_tune" and "verbose" to True,I tried a few times but still showing False, Thank you very much!

``fine_tune`` and ``verbose`` are boolean arguments. If they are omitted, their values are false. If they are presented (just simply ``--verbose``), their values are true.

**Comment by LINSEVENQI** [comment]
> Saving model with best val PSNR is supported from [16dfac2](https://github.com/thangvubk/video-super-resolution/commit/16dfac27fc52ac14f6b38bce71378c9bd1288261)

Thank you very much!!!But I find another problem
-------YOUR SETTINGS_________
          model: VRES
          scale: 3
      train_set: train
        val_set: test/IndMya
     batch_size: 100
  learning_rate: 0.001
     num_epochs: 50
      fine_tune: False
        verbose: False

Contructing dataset...
Training...
100%|██████████| 623/623 [02:20<00:00,  5.06it/s]
My progress bar shows 623 but your display is 622，I downloaded from the dataset link you provided and then processed using matlab.I don't know why。

**Comment by thangvubk** [comment]
``Progressbar2`` is replaced by ``tqdm``, which is more stable, from [0b7cd3d](https://github.com/thangvubk/video-super-resolution/commit/0b7cd3df557a976f70279184e97c813572745dfa).

**Comment by LINSEVENQI** [comment]
> `Progressbar2` is replaced by `tqdm`, which is more stable, from [0b7cd3d](https://github.com/thangvubk/video-super-resolution/commit/0b7cd3df557a976f70279184e97c813572745dfa).

I am using the latest code you provided, just seeing that the number of prompts 623 is inconsistent with the 622 you displayed, So would you like to ask if the number displayed after using tqdm is 623 also?

**Comment by thangvubk** [comment]
Mine is also 623. It is not so important.

**Comment by LINSEVENQI** [comment]
> Mine is also 623. It is not so important.

Thank you! And is the parameter provided in your code with the best model? Because the results of the experiment I ran out according to the parameters provided in the code did not work well.

**Comment by thangvubk** [comment]
The parameters are saved with the best model. I train with 50 epochs and obtain PSNR of 33.31dB on the validation set, which is closed to the results in our report.

**Comment by LINSEVENQI** [comment]
> The parameters are saved with the best model. I train with 50 epochs and obtain PSNR of 33.31dB on the validation set, which is closed to the results in our report.

I am very anxious to bother you again. When I use your code to train with scale=2, the best model shows the PSNR of the val set IndMya and the PSNR of the best model test IndMya dataset when testing is very different，I don't know why does the same dataset have not  the same result for the same model?

**Comment by thangvubk** [comment]
What is the Val and test psnr. Did you change the scale for test to 2.

**Comment by LINSEVENQI** [comment]
> What is the Val and test psnr. Did you change the scale for test to 2.
when scale=2,the Val is 36.583dB and 0.966 ,however test is 33.379dB and 0.935,both using IndMya dataset and the best model.

**Comment by thangvubk** [comment]
I guess you are using ``scale=3`` for testing. You may need to change to ``scale=2`` by ``python test.py --scale 2``

**Comment by LINSEVENQI** [comment]
> I guess you are using `scale=3` for testing. You may need to change to `scale=2` by `python test.py --scale 2`

-------YOUR SETTINGS_________
          model: VRES
     model_path: ./check_point/VRES/2x/best_model.pt
          scale: 2
       test_set: IndMya

Contructing dataset...
Testing...
Img0: PSNR: 26.999 SSIM: 0.868 Time: 1.9951
Img1: PSNR: 36.859 SSIM: 0.964 Time: 0.1880
Img2: PSNR: 34.803 SSIM: 0.953 Time: 0.0150
Img3: PSNR: 32.423 SSIM: 0.939 Time: 0.0140
Img4: PSNR: 35.268 SSIM: 0.961 Time: 0.0140
Img5: PSNR: 33.267 SSIM: 0.914 Time: 0.0150
Img6: PSNR: 32.734 SSIM: 0.923 Time: 0.0140
Img7: PSNR: 34.679 SSIM: 0.956 Time: 0.0140
Average test psnr: 33.379dB
Average test ssim: 0.935
Finish!!!
